Traceback (most recent call last):
  File "./cubes.py", line 89, in <module>
    main()
  File "./cubes.py", line 62, in main
    specification = Specification(spec)
  File "/home/rmbb/CUBES/squares/dsl/specification.py", line 120, in __init__
    self.data_frames['expected_output'] = read_table(self.output)
  File "/home/rmbb/CUBES/squares/dsl/specification.py", line 30, in read_table
    if types.get_type(df[col].dtype) == types.INT:
  File "/home/rmbb/CUBES/squares/types.py", line 36, in get_type
    return Type.Bool
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.7/enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: Bool
