[     3.347][MainProcess][INFO] Parsing specification...
[     3.352][MainProcess][DEBUG] Reading input files...
[     3.360][MainProcess][INFO] Inferred data types for table tests-examples/scythe/recent_posts/tables/015.csv: ['int64', 'string', 'int64', 'string']
[     3.366][MainProcess][INFO] Inferred data types for table tests-examples/scythe/recent_posts/tables/015_o.csv: ['string', 'int64', 'int64', 'int64']
Traceback (most recent call last):
  File "./cubes.py", line 95, in <module>
    main()
  File "./cubes.py", line 68, in main
    specification = Specification(spec)
  File "/home/rmbb/CUBES/squares/dsl/specification.py", line 124, in __init__
    self.generate_r_init()
  File "/home/rmbb/CUBES/squares/dsl/specification.py", line 144, in generate_r_init
    self.r_init += exec_and_return(
  File "/home/rmbb/CUBES/squares/dsl/specification.py", line 19, in exec_and_return
    robjects.r(r_script)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.8/site-packages/rpy2/robjects/__init__.py", line 388, in __call__
    p = _rparse(text=StrSexpVector((string,)))
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 28, in _
    cdata = function(*args, **kwargs)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.8/site-packages/rpy2/rinterface.py", line 785, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in (function (file = "", n = NULL, text = NULL, prompt = "?", keep.source = getOption("keep.source"),  : 
  <text>:1:145: unexpected numeric constant
1: expected_output <- read_csv("tests-examples/scythe/recent_posts/tables/015_o.csv", col_types = cols(KSB_Requirement = col_character(),Principle 1
                                                                                                                                                    ^

